In [25]:
import pandas as pd
data=pd.read_csv("C:\\Users\\Shawaf Khan\\Desktop\\spam.csv",encoding="ISO-8859-1")
data["v1"].replace(to_replace=["ham","spam"],value=[0,1],inplace=True)
data.shape

(5572, 2)

In [26]:
data.drop_duplicates(inplace=True)

In [27]:
data.shape

(5169, 2)

In [28]:
data.columns

Index(['v1', 'v2'], dtype='object')

In [33]:
data.isnull().sum()

v1    0
v2    0
dtype: int64

In [31]:
import numpy as np
import nltk
from nltk.corpus import stopwords
import string

In [38]:
def process(text):
    new=[char for char in text if char not in string.punctuation]
    new=''.join(new)
    clean=[ch for ch in new.split() if ch not in stopwords.words('english') ]
    return clean
    

In [40]:
##To check weather the function is working
data["v2"].head().apply(process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, I, dont, think, goes, usf, lives, around...
Name: v2, dtype: object

In [43]:
from sklearn.feature_extraction.text import CountVectorizer 
skt=CountVectorizer(analyzer=process).fit_transform(data["v2"])


In [46]:
### creating training data and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(skt,data["v1"],test_size=0.20,random_state=0)

In [47]:
skt.shape

(5169, 11495)

In [49]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [51]:
print(classifier.predict(x_train))
print(y_train.values)


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [62]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import accuracy_score
predict=classifier.predict(x_train)
print("Classification Report:   ",classification_report(y_train,predict))
print("Confusion Matrix:   \n",confusion_matrix(y_train,predict))
print("Acurracy:  ",accuracy_score(y_train,predict))

Classification Report:                  precision    recall  f1-score   support

           0       1.00      1.00      1.00      3631
           1       0.98      0.98      0.98       504

    accuracy                           1.00      4135
   macro avg       0.99      0.99      0.99      4135
weighted avg       1.00      1.00      1.00      4135

Confusion Matrix:   
 [[3623    8]
 [  10  494]]
Acurracy:   0.9956469165659009


In [61]:
### REport for test data
predict_test=classifier.predict(x_test)
print("Classification Report:   ",classification_report(y_test,predict_test))
print("Confusion Matrix:  \n ",confusion_matrix(y_test,predict_test))
print("Acurracy:  ",accuracy_score(y_test,predict_test))

Classification Report:                  precision    recall  f1-score   support

           0       0.99      0.97      0.98       885
           1       0.84      0.91      0.88       149

    accuracy                           0.96      1034
   macro avg       0.91      0.94      0.93      1034
weighted avg       0.96      0.96      0.96      1034

Confusion Matrix:  
  [[860  25]
 [ 13 136]]
Acurracy:   0.9632495164410058


In [64]:
print("predicted value:   ",classifier.predict(x_test))
print("Actual values:   ",y_test.values)

predicted value:    [0 0 0 ... 0 0 0]
Actual values:    [0 0 0 ... 0 0 0]


In [66]:
# Creating spam classifier using Logistic regression

In [67]:
x_train1,x_test1,y_train1,y_test=train_test_split(skt,data["v1"],test_size=0.30,random_state=20)

In [71]:
from sklearn.linear_model import LogisticRegression
classifierr=LogisticRegression(solver='liblinear',penalty='l2')
classifierr.fit(x_train1,y_train1)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [76]:
pred=classifierr.predict(x_train1)

print(accuracy_score(y_train1,pred))

0.9972360420121614
